version: '3'
services:
  web:
    build: .
    command: node -r @babel/register node_modules/.bin/sequelize db:migrate
    command: node -r @babel/register node_modules/.bin/sequelize db:seed:all
    command: npm run lint
    command: npm run test
    command: npm run start
    volumes:
      - .:/src/
      - /hioexercises/balance/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yuadnat
