  install_dependencies:
    docker:
      - image: circleci/node:8.11.3-stretch
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repository-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.11.3-stretch
      - image: redis:4.0.9
      - image: postgres:10.4
        environment:
          - POSTGRES_PASSWORD=yuadnat
          - POSTGRES_USER=postgres
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repository-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: posgresql client setup
          command: >
            sudo apt install wget ca-certificates &&
            echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" | sudo tee --append /etc/apt/sources.list.d/pgdg.list &&
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - &&
            echo "deb http://security.debian.org/debian-security jessie/updates main " | sudo tee --append /etc/apt/sources.list &&
            sudo apt update &&
            sudo apt install libssl1.0.0 libpq5 postgresql-client-10
      - run:
          name: lint
          command: npm run lint
      - run:
          name: pg-setup
          command: NODE_ENV=test npm run pg-setup
      - run:
          name: test
command: NODE_ENV=test npm test