type Account {
  id: ID!
  balance: Float!
  availablebalance(context: String): Float!
}

type ReservedBalance {
  id: ID!
  accountid: Int!
  context: String!
  balance: Float!
}

type VirtualBalance {
  id: ID!
  accountid: Int!
  context: String!
  balance: Float!
}