type Account {
  id: ID!
  balance: Float!
  availableBalance(context: String): Float!
}

type ReservedBalance {
  id: ID!
  accountId: Int!
  context: String!
  balance: Float!
}

type VirtualBalance {
  id: ID!
  accountId: Int!
  context: String!
  balance: Float!
}

type Request {
  id: ID!
  uuId: Int!
  accountId: Int!
  reservedBalanceId: Int!
  virtualBalanceId: Int!
  amount: Float!
  resultSet: String!
  requestType: String!
}