type Query {
  account(id: ID!): Account
  reservedBalance(id: ID!): ReservedBalance
  virtualBalance(id: ID!): VirtualBalance
  reservedBalances(account: ID!): [ReservedBalance]!
  virtualBalances(account: ID!): [VirtualBalance]!
}